services:
  brother-scand:
    restart: unless-stopped
    image: ghcr.io/rgarrido03/brother-scand:latest
    network_mode: host
    volumes:
      - "~/Scans:/scans"
      - "./out:/etc/brother-scand"
